Controllers/UtrkeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EvidencijaUtrka.DAL;
using EvidencijaUtrka.Models;
using EvidencijaUtrka.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace EvidencijaUtrka.Controllers
{
    [Authorize]
    public class UtrkeController : Controller
    {
        private readonly IUtrkaRepository _utrkaContext;
        private readonly IUtrkaRezultatRepository _utrkaRezultatContext;

        public UtrkeController(IUtrkaRepository utrkaContext, IUtrkaRezultatRepository utrkaRezultatContext)
        {
            _utrkaContext = utrkaContext;
            _utrkaRezultatContext = utrkaRezultatContext;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_utrkaContext.GetAllUtrke().OrderByDescending(u => u.Datum));
        }

        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var utrka = _utrkaContext.GetUtrka(id);
            if (utrka == null)
            {
                return NotFound();
            }
            else
            {
                utrka.Rezultati = _utrkaRezultatContext.GetAllOfficialUtrkaRezultat(id).OrderBy(r => r.RezultatVrijeme).ToList();
            }

            return View(utrka);
        }

        public IActionResult Administracija()
        {
            return View(_utrkaContext.GetAllUtrke().OrderByDescending(u => u.Datum));
        }

        public IActionResult DetailsAdministracija(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var utrka = _utrkaContext.GetUtrka(id);
            if (utrka == null)
            {
                return NotFound();
            }
            else
            {
                utrka.Rezultati = _utrkaRezultatContext.GetAllUnofficialUtrkaRezultat(id).OrderBy(r => r.RezultatVrijeme).ToList();
            }

            return View(utrka);
        }
        
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Evidencija Utrka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Utrke" asp-action="Index">EvidencijaUtrka</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Utrke" asp-action="Index">Utrke</a>
                        </li>                       
                    </ul>
                    <ul class="navbar-nav ml-auto flex-grow-1">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="Logout" asp-controller="Account">
                                    <button type="submit" class="nav-link btn btn-link py-0"
                                            style="width:auto">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Utrke" asp-action="Administracija">Administracija</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-action="login" asp-controller="account" class="nav-link">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Evidencija Utrka 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>