Controllers/UtrkaRezultatiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EvidencijaUtrka.DAL;
using EvidencijaUtrka.Models;
using EvidencijaUtrka.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace EvidencijaUtrka.Controllers
{
    [Authorize]
    public class UtrkaRezultatiController : Controller
    {
        private readonly IUtrkaRezultatRepository _utrkaRezultatContext;

        public UtrkaRezultatiController(IUtrkaRezultatRepository utrkaRezultatContext)
        {
            _utrkaRezultatContext = utrkaRezultatContext;
        }        
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var utrkaRezultat = _utrkaRezultatContext.GetUtrkaRezultat(id);
            if (utrkaRezultat == null)
            {
                return NotFound();
            }

            return View(utrkaRezultat);
        }

        
        [AllowAnonymous]
        public IActionResult Create(int id)
        {
            ViewData["UtrkaId"] = id;
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public IActionResult Create([Bind("UtrkaRezultatID,Ime,Prezime,RezultatVrijeme,Sluzben,UtrkaID")] UtrkaRezultat utrkaRezultat)
        {
            utrkaRezultat.Sluzben = false;
            if (ModelState.IsValid)
            {
                _utrkaRezultatContext.Add(utrkaRezultat);
                return RedirectToAction("Details", "Utrke", new {id = utrkaRezultat.UtrkaID});
            }
            ViewData["UtrkaID"] = utrkaRezultat.UtrkaID;
            return View(utrkaRezultat);
        }

        
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var utrkaRezultat = _utrkaRezultatContext.GetUtrkaRezultat(id);
            if (utrkaRezultat == null)
            {
                return NotFound();
            }
            return PartialView("_EditRezultatPartial", utrkaRezultat);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("UtrkaRezultatID,Ime,Prezime,RezultatVrijeme,Sluzben,UtrkaID")] UtrkaRezultat utrkaRezultat)
        {
            if (id != utrkaRezultat.UtrkaRezultatID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _utrkaRezultatContext.Update(utrkaRezultat);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UtrkaRezultatExists(utrkaRezultat.UtrkaRezultatID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("DetailsAdministracija", "Utrke", new {id = utrkaRezultat.UtrkaID});
            }            
            return PartialView("_EditRezultatPartial", utrkaRezultat);
        }

        
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var utrkaRezultat = _utrkaRezultatContext.GetUtrkaRezultat(id);
            if (utrkaRezultat == null)
            {
                return NotFound();
            }

            return View(utrkaRezultat);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            int utrkaId = _utrkaRezultatContext.GetUtrkaRezultat(id).UtrkaID;
            bool sluzben = _utrkaRezultatContext.GetUtrkaRezultat(id).Sluzben;
            var utrkaRezultat = _utrkaRezultatContext.Delete(id);
            if (sluzben)
            {
                return RedirectToAction("Details", "Utrke", new { id = utrkaId });
            }
            else
            {
                return RedirectToAction("DetailsAdministracija", "Utrke", new { id = utrkaId });
            }
            
        }

        private bool UtrkaRezultatExists(int id)
        {
            return _utrkaRezultatContext.GetUtrkaRezultat(id) != null;
        }
    }
}

Views/UtrkaRezultati/Create.cshtml
@model EvidencijaUtrka.Models.UtrkaRezultat

@{
    ViewData["Title"] = "Create";
}


<h4>Unesite svoj rezultat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input hidden asp-for="UtrkaID" value="@ViewData["UtrkaId"]" />
            <div class="form-group">
                <label asp-for="Ime" class="control-label"></label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezime" class="control-label"></label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RezultatVrijeme" class="control-label"></label>
                <input asp-for="RezultatVrijeme" class="form-control" />
                <span asp-validation-for="RezultatVrijeme" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <input hidden class="form-check-input" asp-for="Sluzben" />
            </div>
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/UtrkaRezultati/Delete.cshtml
@model UtrkaRezultat
@{
    ViewData["Title"] = "Delete";
}

<h3>Jeste li sigurni za brisanje?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Prezime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RezultatVrijeme)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RezultatVrijeme)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="UtrkaRezultatID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="DetailsAdministracija" asp-controller="Utrke" asp-route-id="@Model.UtrkaID" >Povratak</a>
    </form>
</div>

Views/UtrkaRezultati/Details.cshtml
@model EvidencijaUtrka.Models.UtrkaRezultat

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UtrkaRezultat</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RezultatVrijeme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RezultatVrijeme)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sluzben)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sluzben)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Utrka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Utrka.UtrkaID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.UtrkaRezultatID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/UtrkaRezultati/_EditRezultatPartial.cshtml
@model UtrkaRezultat


<!-- Modal -->
<div class="modal fade" id="rezultat" tabindex="-1" role="dialog" aria-labelledby="rezultatLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="rezultatLabel">Rezultat</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="UtrkaRezultati" asp-action="Edit" method="post">
                    <input type="hidden" asp-for="UtrkaRezultatID" />
                    <div class="form-group">
                        <label asp-for="Ime" class="control-label"></label>
                        <input asp-for="Ime" class="form-control" readonly />
                    </div>
                    <div class="form-group">
                        <label asp-for="Prezime" class="control-label"></label>
                        <input asp-for="Prezime" class="form-control" readonly />
                    </div>
                    <div class="form-group">
                        <label asp-for="RezultatVrijeme" class="control-label"></label>
                        <input asp-for="RezultatVrijeme" class="form-control" readonly />
                    </div>
                    <div class="form-group">
                        <label asp-for="Sluzben" class="control-label"></label>
                        <input asp-for="Sluzben" class="form-control" />
                    </div>
                    <div class="form-group">
                        <input hidden asp-for="UtrkaID" class="form-control" />
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Zatvori</button>
                        <input type="submit" value="Spremi" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>